import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MainAppFooter, MainAppHeader } from "@/common/components";

const machinaFont = localFont({
  src: [
    {
      path: "../assets/fonts/NeueMachina-Light.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../assets/fonts/NeueMachina-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/NeueMachina-Ultrabold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${machinaFont.className} antialiased`}>
        <MainAppHeader />
        {children}
        <MainAppFooter />
      </body>
    </html>
  );
}
